version: '3.7'
services:
  matterbridge:
    build:
      context: .
      args:
        DISCORD_TOKEN: ${DISCORD_TOKEN}
      network: "host"
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN
    network_mode: "host"
#    command: -debug
