[irc]
  [irc.dtek]
  Server = "localhost:6667"
  Nick = "Discord"
  SkipTLSVerify = true

[discord]
  [discord.clipboard]
  Token = DISCORD_TOKEN
  Server = "Datateknologsektionen, Chalmers Studentkår"


[general]
RemoteNickFormat="<{NICK}> "

[[gateway]]
  name = "mygateway"
  enable = true

  [[gateway.inout]]
  account ="irc.dtek"
  channel = "#dtek"

  [[gateway.inout]]
  account = "discord.clipboard"
  channel = "irc"
